[package]
name = "huffman"
version = "0.1.0"
authors = ["Ivan Veselov <veselov@gmail.com>"]
edition = "2018"

[dependencies]
log = { version = "0.4", features = ["max_level_debug", "release_max_level_warn"] }
env_logger = "0.7"

[dev-dependencies]
quickcheck = "0.9"
quickcheck_macros = "0.9"
